### ISSUE TITLE
PayPal Init

### ISSUE THREAD

**Issue by reka** [wirecard/paymentSDK-php#3]
As developer of a shop-plugin based on EE I am able to integrate PayPal as payment method, so that consumers of my web-shop are able to pay via PayPal.

Acceptance criteria:
 - example with documentation is available
 - As a developer I can use the example without changes "out-of-the-box" on my web-server.
 - php-versions >= 5.6 are supported
 - Successful payments and errors are handled.

**Comment by reka** [comment]
## Tasks for pay:
- [ ] create entity PayPalTransaction
- [ ] create request mapper: PayPalTransaction => request object for Engine
- [ ] create entity for InteractionResponse
- [ ] create entity for Failure
- [ ] create response mapper
- [ ] create class for config
- [ ] create transaction service
- [ ] implement the pay method: request to Engine
